name: NodeJS with Grunt

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Git merge from main into deploy branch
      run: |
        git pull
        git checkout deploy-pages
        GIT_MERGE_AUTOEDIT=no git merge origin/main
    - name: Build
      run: |
        npx honkit build
        rm -rf docs
        cp _book docs
        git add -A
        git commit -m "deploy pages `date +%Y-%m-%dT%H:%M:%S`"
        git push
